version: '3.7'

services:
  database_pedefast:
    image: postgres
    container_name: database_pedefast
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pedefast
      - POSTGRES_DB=pedefast
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
